=== smee/elateXam/taskmodel/taskmodel-core/jaxb/complexTaskDef.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 U (http://www.xmlspy.com) by tb (ul) -->
<xs:schema targetNamespace="http://complex.taskmodel.thorstenberger.de/complexTaskDef" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns="http://complex.taskmodel.thorstenberger.de/complexTaskDef" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" jaxb:version="1.0">
	<!--
Change Log:

- 16.06.05: mc-config: negative points geändert, um untersch. viele Punkte für richtige und falsche Antworten abziehen zu können
- 17.06.05: mcSubTaskDef global und "choice" eingeführt, um sich gegenseitig ausschließende Aufgaben zu modellieren
- 05.01.06: config global, da bei allen taskblocks vorhanden
- 05.01.06: Lueckentext nicht mehr mixed content, funzt nich in JAXFront
- 24.01.06 annotation für JAXB: generateIsSetMethod entfernt
- 12.06.06 neuer Aufgabentyp: paintSubTaskDef hinzugefügt
-->
	<xs:element name="complexTaskDef">
		<xs:annotation>
			<xs:documentation>task definition (homework, exam etc.) that consists of several sub tasks</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="config">
					<xs:complexType>
						<xs:all>
							<xs:element name="time" minOccurs="0">
								<xs:annotation>
									<xs:documentation>available time in minutes to solve the task,
unbounded if left empty</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:int">
										<xs:minInclusive value="0"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="tries" default="1">
								<xs:annotation>
									<xs:documentation>Number of possible tries to solve the task.
Every new try results in a random aggregation of subtasks (and possibly answer combinations)</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:int">
										<xs:minInclusive value="1"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="tasksPerPage">
								<xs:annotation>
									<xs:documentation>Number of tasks that are rendered per page, therefore implies the number of pages.</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:int">
										<xs:minInclusive value="1"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="kindnessExtensionTime" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Kindness extension in minutes. After expiration of the official processing time, the student can still edit his solution until this time expires.</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:int">
										<xs:minInclusive value="0"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:all>
					</xs:complexType>
				</xs:element>
				<xs:element name="title" type="xs:string"/>
				<xs:element name="description" type="xs:string"/>
				<xs:element name="startText" type="xs:string" minOccurs="0"/>
				<xs:element name="category" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Divide subtask blocks into categories.

Attributes: title - name of the category (opt.)
preserveOrderOfBlocks - soll die Reihenfolge der Blöcke erhalten bleiben oder zufällig festgelegt werden?
mixAllSubTasks -  damit werden alle Aufgaben aus allen Blöcken in zufälliger Reihenfolge angeordnet, überschreibt preserveOrderOfBlocks und preserveOrder der Aufgaben in Blöcken</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:choice maxOccurs="unbounded">
							<xs:element name="mcTaskBlock">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="config"/>
										<xs:element name="mc-config">
											<xs:complexType>
												<xs:choice>
													<xs:element name="regular">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="negativePoints">
																	<xs:simpleType>
																		<xs:restriction base="xs:float">
																			<xs:minInclusive value="0"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="different">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="correctAnswerNegativePoints">
																	<xs:simpleType>
																		<xs:restriction base="xs:float">
																			<xs:minInclusive value="0"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
																<xs:element name="incorrectAnswerNegativePoints">
																	<xs:simpleType>
																		<xs:restriction base="xs:float">
																			<xs:minInclusive value="0"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:choice>
											</xs:complexType>
										</xs:element>
										<xs:choice maxOccurs="unbounded">
											<xs:element ref="mcSubTaskDef"/>
											<xs:element name="choice">
												<xs:complexType>
													<xs:sequence>
														<xs:element ref="mcSubTaskDef" maxOccurs="unbounded"/>
													</xs:sequence>
												</xs:complexType>
											</xs:element>
										</xs:choice>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="clozeTaskBlock">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="config"/>
										<xs:element name="cloze-config">
											<xs:complexType>
												<xs:attribute name="negativePoints" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:float">
															<xs:minInclusive value="0"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="ignoreCase" type="xs:boolean" use="optional"/>
											</xs:complexType>
										</xs:element>
										<xs:choice maxOccurs="unbounded">
											<xs:element ref="clozeSubTaskDef"/>
											<xs:element name="choice">
												<xs:complexType>
													<xs:sequence>
														<xs:element ref="clozeSubTaskDef" maxOccurs="unbounded"/>
													</xs:sequence>
												</xs:complexType>
											</xs:element>
										</xs:choice>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="textTaskBlock">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="config"/>
										<xs:choice maxOccurs="unbounded">
											<xs:element ref="textSubTaskDef"/>
											<xs:element name="choice">
												<xs:complexType>
													<xs:sequence>
														<xs:element ref="textSubTaskDef" maxOccurs="unbounded"/>
													</xs:sequence>
												</xs:complexType>
											</xs:element>
										</xs:choice>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="mappingTaskBlock">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="config"/>
										<xs:element name="mapping-config">
											<xs:complexType>
												<xs:attribute name="negativePoints" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:float">
															<xs:minInclusive value="0"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
										<xs:choice maxOccurs="unbounded">
											<xs:element ref="mappingSubTaskDef"/>
											<xs:element name="choice">
												<xs:complexType>
													<xs:sequence>
														<xs:element ref="mappingSubTaskDef" maxOccurs="unbounded"/>
													</xs:sequence>
												</xs:complexType>
											</xs:element>
										</xs:choice>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="paintTaskBlock">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="config"/>
										<xs:choice maxOccurs="unbounded">
											<xs:element ref="paintSubTaskDef"/>
											<xs:element name="choice">
												<xs:complexType>
													<xs:sequence>
														<xs:element ref="paintSubTaskDef" maxOccurs="unbounded"/>
													</xs:sequence>
												</xs:complexType>
											</xs:element>
										</xs:choice>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:choice>
						<xs:attribute name="title" type="xs:string" use="optional"/>
						<xs:attribute name="preserveOrderOfBlocks" type="xs:boolean" use="required"/>
						<xs:attribute name="id" type="xs:string" use="required"/>
						<xs:attribute name="mixAllSubTasks" type="xs:boolean" use="required"/>
						<xs:attribute name="tasksPerPage" use="optional">
							<xs:simpleType>
								<xs:restriction base="xs:int">
									<xs:minInclusive value="0"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="category_id">
			<xs:selector xpath=".//category"/>
			<xs:field xpath="@id"/>
		</xs:unique>
		<xs:unique name="subtask_id">
			<xs:selector xpath="./*/*/*"/>
			<xs:field xpath="@id"/>
		</xs:unique>
	</xs:element>
	<xs:group name="taskblock">
		<xs:all>
			<xs:element name="mc"/>
		</xs:all>
	</xs:group>
	<xs:group name="blockconfig">
		<xs:sequence/>
	</xs:group>
	<xs:element name="mcSubTaskDef">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="problem" type="xs:string"/>
				<xs:element name="hint" type="xs:string" minOccurs="0"/>
				<xs:element name="displayedAnswers">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="correct" maxOccurs="unbounded">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="id" type="xs:string" use="required"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="incorrect" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="id" type="xs:string" use="required"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="category" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="singleSelect"/>
						<xs:enumeration value="multipleSelect"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="minCorrectAnswers" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="maxCorrectAnswers" type="xs:int" use="optional"/>
		</xs:complexType>
		<xs:unique name="answer_id">
			<xs:selector xpath="./*"/>
			<xs:field xpath="@id"/>
		</xs:unique>
	</xs:element>
	<xs:element name="textSubTaskDef">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="problem" type="xs:string"/>
				<xs:element name="hint" type="xs:string" minOccurs="0"/>
				<xs:element name="correctionHint" type="xs:string" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="textFieldWidth" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="textFieldHeight" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="clozeSubTaskDef">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="problem" type="xs:string" minOccurs="0"/>
				<xs:element name="hint" type="xs:string" minOccurs="0"/>
				<xs:element name="cloze">
					<xs:complexType mixed="false">
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element name="text" type="xs:string"/>
							<xs:element name="gap">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="correct" type="xs:string" maxOccurs="unbounded"/>
									</xs:sequence>
									<xs:attribute name="inputLength" use="optional">
										<xs:simpleType>
											<xs:restriction base="xs:int">
												<xs:minInclusive value="1"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="ignoreCase" type="xs:boolean" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="mappingSubTaskDef">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="problem" type="xs:string"/>
				<xs:element name="hint" type="xs:string" minOccurs="0"/>
				<xs:element name="concept" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="name" type="xs:string" use="required"/>
						<xs:attribute name="correctAssignmentID" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="assignment" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="id" type="xs:string" use="required"/>
						<xs:attribute name="name" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
		</xs:complexType>
		<xs:key name="assignmentKey">
			<xs:selector xpath="./assignment"/>
			<xs:field xpath="@id"/>
		</xs:key>
		<xs:keyref name="correctAssignmentKeyRef" refer="assignmentKey">
			<xs:selector xpath="./concept"/>
			<xs:field xpath="@correctAssignmentID"/>
		</xs:keyref>
	</xs:element>
	<xs:element name="config">
		<xs:complexType>
			<xs:attribute name="pointsPerTask" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:float">
						<xs:minInclusive value="0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="noOfSelectedTasks" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="preserveOrder" type="xs:boolean" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="paintSubTaskDef">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="problem" type="xs:string"/>
				<xs:element name="images" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="mutableTemplateImage" type="xs:base64Binary" minOccurs="0"/>
							<xs:element name="immutableBackgroundImage" type="xs:base64Binary" minOccurs="0"/>
							<xs:element name="correctionTemplateImage" type="xs:base64Binary" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="textualAnswer" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="textFieldWidth" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:int">
										<xs:minInclusive value="1"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="textFieldHeight" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:int">
										<xs:minInclusive value="1"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="hint" type="xs:string" minOccurs="0"/>
				<xs:element name="colorChangeable" type="xs:boolean" minOccurs="0"/>
				<xs:element name="strokewidthChangeable" type="xs:boolean" minOccurs="0"/>
				<xs:element name="correctionHint" type="xs:string" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== smee/elateXam/elateXam-integrationtest/src/test/resources/testklausur.xml
<?xml version="1.0"?>
<!-- edited with XMLSPY v5 U (http://www.xmlspy.com) by tb (ul) -->
<!--Sample XML file generated by XMLSPY v5 U (http://www.xmlspy.com)-->
<complexTaskDef xmlns="http://complex.taskmodel.thorstenberger.de/complexTaskDef" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://complex.taskmodel.thorstenberger.de/complexTaskDef D:\elateworkspace\taskmodel\taskmodel-schema\src\main\jaxb\complexTaskDef.xsd">
	<config>
		<time>45</time>
		<tries>1000</tries>
		<tasksPerPage>2</tasksPerPage>
		<correctionMode>
			<regular/>
		</correctionMode>
	</config>
	<title>&#xDC;bungsklausur</title>
	<description>Diese &#xDC;bungsklausur hat zwei Funktionen: Einerseits sollen Sie mit der Benutzeroberfl&#xE4;che des Klausur-Moduls vertraut gemacht werden. Sie sollen lernen, wie die Multiple-Choice-Aufgaben funktionieren, wie Zuordnungsaufgaben aufgebaut sind, was sich hinter L&#xFC;ckentext-Aufgaben verbirgt und wie die Eingabe freier Antworten funktioniert. Dazu verwenden wir Aufgaben, die nicht unbedingt dem Vorlesungsstoff entnommen worden sind und nicht in jedem Fall mit tierischem Ernst zu nehmen sind. Andere Aufgaben sind n&#xE4;her am Klausurstoff und sollen Ihnen eine Vorstellung von Art und Umfang der Fragestellung vermitteln.</description>
	<startText>Hiermit starten Sie die &#xDC;bungsklausur. Sie k&#xF6;nnen zum &#xDC;ben mehrere Versuche starten.</startText>
	<category id="Kat_MC" title="Multiple Choice">
		<mcTaskBlock>
			<config noOfSelectedTasks="4" pointsPerTask="5.0" preserveOrder="false"/>
			<mc-config>
				<regular>
					<negativePoints>1.0</negativePoints>
				</regular>
			</mc-config>
			<mcSubTaskDef id="a1" category="multipleSelect" maxCorrectAnswers="4" minCorrectAnswers="1">
			
				<problem>bla bla bla</problem>
				<hint>bla bla bla</hint>
				<displayedAnswers>5</displayedAnswers>
				<correct id="c1">
  correctAnswer
</correct>
				<correct id="c2">
  correctAnswer
</correct>
				<correct id="c3">
  correctAnswer
</correct>
				<correct id="c4">
  correctAnswer
</correct>
				<incorrect id="i1">
  correctAnswer
</incorrect>
				
				<incorrect id="i2">
  correctAnswer
</incorrect>
				<incorrect id="i3">
  correctAnswer
</incorrect>
				<incorrect id="i4">
  correctAnswer
</incorrect>
			</mcSubTaskDef>
			<mcSubTaskDef id="a2" category="multipleSelect" maxCorrectAnswers="4" minCorrectAnswers="1">
				<problem>bla bla bla</problem>
				<hint>bla bla bla</hint>
				<displayedAnswers>5</displayedAnswers>
				<correct id="c1">
  correctAnswer
</correct>
				<correct id="c2">
  correctAnswer
</correct>
				<correct id="c3">
  correctAnswer
</correct>
				<correct id="c4">
  correctAnswer
</correct>
				<incorrect id="i1">
  correctAnswer
</incorrect>
				<incorrect id="i2">
  correctAnswer
</incorrect>
				<incorrect id="i3">
  correctAnswer
</incorrect>
				<incorrect id="i4">
  correctAnswer
</incorrect>
			</mcSubTaskDef>
			<mcSubTaskDef id="a3" category="multipleSelect" maxCorrectAnswers="4" minCorrectAnswers="1">
				<problem>bla bla bla</problem>
				<hint>bla bla bla</hint>
				<displayedAnswers>5</displayedAnswers>
				<correct id="c1">
  correctAnswer
</correct>
				<correct id="c2">
  correctAnswer
</correct>
				<correct id="c3">
  correctAnswer
</correct>
				<correct id="c4">
  correctAnswer
</correct>
				<incorrect id="i1">
  correctAnswer
</incorrect>
				<incorrect id="i2">
  correctAnswer
</incorrect>
				<incorrect id="i3">
  correctAnswer
</incorrect>
				<incorrect id="i4">
  correctAnswer
</incorrect>
			</mcSubTaskDef>
			<mcSubTaskDef id="a4" category="multipleSelect" maxCorrectAnswers="4" minCorrectAnswers="1">
				<problem>bla bla bla</problem>
				<hint>bla bla bla</hint>
				<displayedAnswers>5</displayedAnswers>
				<correct id="c1">
  correctAnswer
</correct>
				<correct id="c2">
  correctAnswer
</correct>
				<correct id="c3">
  correctAnswer
</correct>
				<correct id="c4">
  correctAnswer
</correct>
				<incorrect id="i1">
  correctAnswer
</incorrect>
				<incorrect id="i2">
  correctAnswer
</incorrect>
				<incorrect id="i3">
  correctAnswer
</incorrect>
				<incorrect id="i4">
  correctAnswer
</incorrect>
			</mcSubTaskDef>
		</mcTaskBlock>
	</category>
	<category id="Kat_Map" title="Zuordnung">
		<mappingTaskBlock>
			<config noOfSelectedTasks="3" pointsPerTask="5.0" preserveOrder="false"/>
			<mapping-config negativePoints="1.0"/>
			<mappingSubTaskDef id="map1">
				<problem>bla bla bla</problem>
				<concept name="name">
					<correctAssignmentID>4</correctAssignmentID>
				</concept>
				<concept name="name">
					<correctAssignmentID>1</correctAssignmentID>
				</concept>
				<concept name="name">
					<correctAssignmentID>5</correctAssignmentID>
				</concept>
				<concept name="name">
					<correctAssignmentID>2</correctAssignmentID>
				</concept>
				<concept name="name">
					<correctAssignmentID>3</correctAssignmentID>
				</concept>
				<assignment id="1" name="name"/>
				<assignment id="2" name="name"/>
				<assignment id="3" name="name"/>
				<assignment id="4" name="name"/>
				<assignment id="5" name="name"/>
			</mappingSubTaskDef>
			<mappingSubTaskDef id="map2">
				<problem>bla bla bla</problem>
				<concept name="name">
					<correctAssignmentID>1</correctAssignmentID>
				</concept>
				<concept name="name">
					<correctAssignmentID>4</correctAssignmentID>
				</concept>
				<concept name="name">
					<correctAssignmentID>5</correctAssignmentID>
				</concept>
				<concept name="name">
					<correctAssignmentID>3</correctAssignmentID>
				</concept>
				<concept name="name">
					<correctAssignmentID>2</correctAssignmentID>
				</concept>
				<assignment id="1" name="name"/>
				<assignment id="2" name="name"/>
				<assignment id="3" name="name"/>
				<assignment id="4" name="name"/>
				<assignment id="5" name="name"/>
			</mappingSubTaskDef>
			<mappingSubTaskDef id="map3">
				<problem>bla bla bla</problem>
				<concept name="name">
					<correctAssignmentID>3</correctAssignmentID>
				</concept>
				<concept name="name">
					<correctAssignmentID>3</correctAssignmentID>
				</concept>
				<concept name="name">
					<correctAssignmentID>1</correctAssignmentID>
				</concept>
				<concept name="name">
					<correctAssignmentID>2</correctAssignmentID>
				</concept>
				<concept name="name">
					<correctAssignmentID>5</correctAssignmentID>
				</concept>
				<assignment id="1" name="name"/>
				<assignment id="2" name="name"/>
				<assignment id="3" name="name"/>
				<assignment id="4" name="name"/>
				<assignment id="5" name="name"/>
			</mappingSubTaskDef>
		</mappingTaskBlock>
	</category>
	<category id="Kat_Cloze" title="L&#xFC;ckentext">
		<clozeTaskBlock>
			<config noOfSelectedTasks="3" pointsPerTask="5.0" preserveOrder="false"/>
			<cloze-config ignoreCase="true" negativePoints="1.0"/>
			<clozeSubTaskDef id="cloze1">
				<problem>bla bla bla</problem>
				<cloze>
					<text>bla bla bla</text>
					<gap inputLength="25">
						<correct>
  correctAnswer
</correct>
					</gap>
					<text>bla bla bla</text>
					<gap inputLength="25">
						<correct>
  correctAnswer
</correct>
					</gap>
					<text>bla bla bla</text>
					<gap inputLength="25">
						<correct>
  correctAnswer
</correct>
					</gap>
					<text>bla bla bla</text>
					<gap inputLength="25">
						<correct>
  correctAnswer
</correct>
					</gap>
					<text>bla bla bla</text>
					<gap inputLength="25">
						<correct>
  correctAnswer
</correct>
					</gap>
					<text>bla bla bla</text>
				</cloze>
			</clozeSubTaskDef>
			<clozeSubTaskDef id="cloze2">
				<problem>bla bla bla</problem>
				<cloze>
					<text>bla bla bla</text>
					<gap inputLength="25">
						<correct>
  correctAnswer
</correct>
					</gap>
					<text>bla bla bla</text>
					<gap inputLength="25">
						<correct>
  correctAnswer
</correct>
					</gap>
					<text>bla bla bla</text>
					<gap inputLength="25">
						<correct>
  correctAnswer
</correct>
					</gap>
					<text>bla bla bla</text>
					<gap inputLength="25">
						<correct>
  correctAnswer
</correct>
					</gap>
					<text>bla bla bla</text>
					<gap inputLength="25">
						<correct>
  correctAnswer
</correct>
					</gap>
					<text>bla bla bla</text>
				</cloze>
			</clozeSubTaskDef>
			<clozeSubTaskDef id="cloze3">
				<problem>bla bla bla</problem>
				<cloze>
					<text>bla bla bla</text>
					<gap inputLength="25">
						<correct>
  correctAnswer
</correct>
					</gap>
					<text>bla bla bla</text>
					<gap inputLength="25">
						<correct>
  correctAnswer
</correct>
					</gap>
					<text>bla bla bla</text>
					<gap inputLength="25">
						<correct>
  correctAnswer
</correct>
					</gap>
					<text>bla bla bla</text>
					<gap inputLength="25">
						<correct>
  correctAnswer
</correct>
					</gap>
					<text>bla bla bla</text>
					<gap inputLength="25">
						<correct>
  correctAnswer
</correct>
					</gap>
					<text>bla bla bla</text>
				</cloze>
			</clozeSubTaskDef>
		</clozeTaskBlock>
	</category>
	<category id="Kat_Text" title="Freier Text">
		<textTaskBlock>
			<config noOfSelectedTasks="1" pointsPerTask="5.0" preserveOrder="false"/>
			<textSubTaskDef id="text1">
				<problem>bla bla bla</problem>
				<correctionHint>hint hint</correctionHint>
			</textSubTaskDef>
		</textTaskBlock>
	</category>
	<revisions>
		<revision author="berger" date="1238976575748" serialNumber="1"/>
	</revisions>
</complexTaskDef>
